name: Run Tests and Publish Package

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage/coverage-final.json
          flags: unittests
          name: codecov-coverage

  publish:
    needs: tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Debug NPM Token
        run: |
          echo "NPM_TOKEN is set: $([[ -n "$NPM_TOKEN" ]] && echo "YES" || echo "NO")"
          echo "NPM_TOKEN length: ${#NPM_TOKEN}"
          echo "First 10 chars: ${NPM_TOKEN:0:10}"
          echo "Last 10 chars: ${NPM_TOKEN: -10}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}

      - name: Test NPM Auth
        run: |
          npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}

      - name: Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}

